# Generated by Django 5.2 on 2025-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Alien ID', 'Alien ID')], default='', max_length=50, verbose_name='National ID')),
                ('Id_Number', models.BigIntegerField()),
                ('Open_Date', models.DateTimeField()),
                ('Title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Other', 'Other')], default='', max_length=10, verbose_name='Title')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField()),
                ('Kra_Pin', models.BigIntegerField()),
                ('Country', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('Postal_Code', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
