# Generated by Django 5.2 on 2025-04-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_contactpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='InsertContact',
        ),
    ]
