# Generated by Django 5.2 on 2025-04-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_rename_contactpage_insertcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsertContact',
            new_name='Contact',
        ),
    ]
