# Generated by Django 5.2 on 2025-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_rename_insertcontact_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdrawal'), ('3', 'Other')], default='', max_length=10, verbose_name='Transaction')),
                ('Amount', models.BigIntegerField()),
            ],
        ),
    ]
