# Generated by Django 5.2 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdrawal'), ('3', 'Other')], default='', max_length=10, verbose_name='Transaction')),
                ('Amount', models.BigIntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
