# Generated by Django 5.2 on 2025-04-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_transactions_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
